name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt install -y gcc g++ make cmake freeglut3-dev libsfml-dev

    - name: CMake build
      run: |
        cmake -B build
        cmake --build build -j 4
